### ISSUE TITLE
Topmost Playlist Obscured

### ISSUE THREAD

**Issue by swishkin** [JulienMaille/dribbblish-dynamic-theme#153]
**Describe the bug** 
Topmost playlist is partially obscured even when scrolled to top. The theme has a fade-out overlay on the top and bottom of the scrollable sidebar, but the fade-out overlay still applies to the topmost item on the sidebar, even if the list is scrolled all the way up.

**To Reproduce**
1. Start Spotify with Dribbblish theme applied
2. View side panel

**Screenshots**

![image](https://user-images.githubusercontent.com/19404743/148655654-9b36643c-a208-4945-a84f-b14df7cc110b.png)

**Logs**

```console
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2820955)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2823539)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2367138
    at Ca (https://xpui.app.spotify.com/vendor~xpui.js:29:3064901)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:3088633)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3303914)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:3034437)
    at Rs (https://xpui.app.spotify.com/vendor~xpui.js:29:3088412)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:3073291)
    at gs (https://xpui.app.spotify.com/vendor~xpui.js:29:3072213)
c @ vendor~xpui.js:29
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

---

### Info for Contributors:

**Versions**
OS: `Windows v10.0.17763`
Spotify: `v1.1.76.447`
Spicetify: `v2.8.3`
Dribbblish: `v4.1.1-0e50a92`

**Extensions**
- dribbblish-dynamic.js

**Settings**
```json
{
    "EXPORTED_WITH": "4.1.1",
    "showLoadingScreen": false,
    "openSettingsInfo": true,
    "showSearchBox": true,
    "rightBigCover": true,
    "roundSidebarIcons": false,
    "sidebarHoverAnimation": true,
    "sidebarGapLeft": 5,
    "sidebarGapRight": 32,
    "winTopBar": "none-padding",
    "playbarShadow": true,
    "playbarTransition": true,
    "playerControlsStyle": "spotify",
    "showAlbumInfoInPlaybar": false,
    "hideAds": false,
    "fadeDuration": 0.5,
    "customCss": "",
    "colorSelectionAlgorithm": "static",
    "colorOverride": "#ff7f00",
    "colorSelectionMode": "default",
    "lightModeLuminance": 0.6,
    "darkModeLuminance": 0.2,
    "theme": "dark",
    "darkModeOnTime": "20:00",
    "darkModeOffTime": "06:00",
    "bgTheme": "bw"
}
```

**Comment by SendNukez** [comment]
This is because the css class of an element that was used inside the script to hide the shadow has changed. I have to find out which element has changed and change it in the css-map.

**Comment by SendNukez** [comment]
This is now fixed, you just have to run `spicetify restore backup apply` to pull the latest css-map.

**Comment by swishkin** [comment]
This issue still occurs in the below version:

OS: Windows v10.0.19044
Spotify: v1.1.79.763
Spicetify: v2.9.1
Dribbblish: v4.1.2-827c9f3

The issue is most pronounced when Spotify is maximized on a portrait monitor. In my case, it's vertical, maximized on a 1440p monitor.

Spotify Maximized, 1442x2520:
![image](https://user-images.githubusercontent.com/19404743/156294705-7589afeb-b44e-4be1-bbfe-67bbae9e00c0.png)

Spotify window: 1440x769
![image](https://user-images.githubusercontent.com/19404743/156294904-e8b3a329-9d1d-463d-ac56-b5b40752206e.png)

Let me know if you need anything else to troubleshoot/bugfix.
