### ISSUE TITLE
[BUG] Previous tracks album stays put

### ISSUE THREAD

**Issue by gahtv** [JulienMaille/dribbblish-dynamic-theme#37]
**Describe the bug**
Previous tracks album stays put when skipping track/waiting for track to finish

**To Reproduce**
1. Play song
2. Skip to another
3. Observe

**Screenshots**
![image](https://user-images.githubusercontent.com/20805878/134817392-ff12da99-dfec-4b21-b978-d0569961cc39.png)
![image](https://user-images.githubusercontent.com/20805878/134817405-8fc03b1a-edb3-4671-81f9-923166e46b53.png)
Extreme example when an ad gets played
![image](https://user-images.githubusercontent.com/20805878/134817467-bd9c9ec9-35a8-4ca4-be99-652b6a66e745.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 11
 - Version [e.g. 22]: 22463.1000
 - Spotify version: 1.1.68.632.g2b11de83 

**Logs**
```console
vendor~xpui.js:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2353172)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2355454)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2048746
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2595327)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2619179)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2618958)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2603729)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2602651)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2565107
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2565052)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564987)
    at Es (https://xpui.app.spotify.com/vendor~xpui.js:29:2603150)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2629563)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2632674)
    at https://xpui.app.spotify.com/xpui.js:1:1034172
(anonymous) @ vendor~xpui.js:1
xpui.js:1 Uncaught (in promise) Error: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at l.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
pubads_impl_2021091501.js:6 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("1"). Valid values: 0,1.
(anonymous) @ pubads_impl_2021091501.js:6
pubads_impl_2021091501.js:6 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("0"). Valid values: 2,0,1.
(anonymous) @ pubads_impl_2021091501.js:6
ads-iframe-internal-click-tracking.js:6 Spotify Ads Iframe Click Tracking origin URL may have changed: https://xpui.app.spotify.com
adsIframeLog @ ads-iframe-internal-click-tracking.js:6
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/754.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by JulienMaille** [comment]
Looks like I forgot to push the .js file in my latest commit. This should be fixed now

**Comment by gahtv** [comment]
Yeah, just downloaded it and it seems to be fixed. Thanks!

**Comment by Jnss98b** [comment]
@JulienMaille I did a fresh install of both spicetify and the theme itself but the issue is still here for me
